/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class barang_masuk extends javax.swing.JFrame {

    /**
     * Creates new form barang_masuk
     */
    public barang_masuk() {
        initComponents();
        tampil_combo();
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbarangmasuk = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbnomorfaktur = new javax.swing.JComboBox<>();
        ok = new javax.swing.JButton();
        hapusbarangkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        tanggalbarangmasuk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        no_masuk = new javax.swing.JTextField();
        nama_supplier = new javax.swing.JTextField();
        simpantransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Barang Masuk");

        tblbarangmasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "No. Masuk", "No. Faktur", "Nama Supplier", "Nama Barang", "Jumlah", "Tanggal"
            }
        ));
        tblbarangmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangmasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbarangmasuk);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Nama Supplier");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Tanggal");

        cmbnomorfaktur.setEditable(true);
        cmbnomorfaktur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbnomorfaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnomorfakturActionPerformed(evt);
            }
        });

        ok.setText("OK");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        hapusbarangkeluar.setText("Hapus");
        hapusbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbarangkeluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Jumlah");

        nama_barang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nama_barang.setEnabled(false);
        nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barangActionPerformed(evt);
            }
        });
        nama_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nama_barangKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nama_barangKeyTyped(evt);
            }
        });

        jumlah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jumlah.setEnabled(false);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });

        tanggalbarangmasuk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tanggalbarangmasuk.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Nomor Faktur");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Nomor Masuk");

        no_masuk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        nama_supplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nama_supplier.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hapusbarangkeluar)
                        .addGap(18, 18, 18)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_masuk)
                            .addComponent(cmbnomorfaktur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama_barang)
                            .addComponent(jumlah)
                            .addComponent(tanggalbarangmasuk)
                            .addComponent(nama_supplier))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(no_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbnomorfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tanggalbarangmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusbarangkeluar)
                    .addComponent(ok))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        simpantransaksi.setText("Simpan Transaksi");
        simpantransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpantransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simpantransaksi)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(403, 403, 403)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpantransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void tampil_combo()
    {
        try {
        Connection con = koneksi.getKoneksi();
        Statement stt = con.createStatement();
        String sql = "select no_faktur from tbl_transaksi_pembelian order by no_faktur asc";      
        ResultSet res = stt.executeQuery(sql);                               
        cmbnomorfaktur.addItem("==Pilih==");
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            
            cmbnomorfaktur.addItem((String) ob[0]);                                      
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void tampil()
    {
        try {
        Connection con = koneksi.getKoneksi();
        Statement stt = con.createStatement();
        String sql = "select nama_supplier, nama_barang, jumlah from tbl_transaksi_pembelian where no_faktur='"+cmbnomorfaktur.getSelectedItem()+"'";  
        ResultSet res = stt.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0]=  res.getString(1);
            ob[1]=  res.getString(2);
            ob[2]=  res.getString(3);
            
            nama_supplier.setText((String) ob[0]);
            nama_barang.setText((String) ob[1]);
            jumlah.setText((String) ob[2]);
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    
    public void tanggal()
    {
        Date ys= new Date();
        SimpleDateFormat s= new SimpleDateFormat("dd-MM-yyyy");
        tanggalbarangmasuk.setText(s.format(ys));
    }
    
    private void tblbarangmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangmasukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbarangmasukMouseClicked

    private void cmbnomorfakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnomorfakturActionPerformed
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_cmbnomorfakturActionPerformed

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbarangmasuk.getModel();
        model.addRow(new Object[]{
            no_masuk.getText(), cmbnomorfaktur.getSelectedItem(), nama_supplier.getText(), nama_barang.getText(), jumlah.getText(), tanggalbarangmasuk.getText()});
    }//GEN-LAST:event_okMouseClicked

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        if(no_masuk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nomor Masuk Tidak Boleh Kosong");

        }else if(cmbnomorfaktur.getSelectedItem().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nomor Faktur Tidak Boleh Kosong");

        }else if(nama_supplier.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nama Supplier Tidak Boleh Kosong");

        }else if(nama_barang.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nama Barang Tidak Boleh Kosong");

        }else if(jumlah.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Jumlah Barang Masuk Tidak Boleh Kosong");

        }else if(tanggalbarangmasuk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Tanggal Barang Masuk Tidak Boleh Kosong");

        }
    }//GEN-LAST:event_okActionPerformed

    private void hapusbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbarangkeluarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbarangmasuk.getModel();
        int row = tblbarangmasuk.getSelectedRow();
        if(row>=0){
            int ok=JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(ok==0){
                model.removeRow(row);
            }
        }
    }//GEN-LAST:event_hapusbarangkeluarActionPerformed

    private void nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nama_barangActionPerformed

    private void nama_barangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_barangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barangKeyReleased

    private void nama_barangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_barangKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barangKeyTyped

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void simpantransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpantransaksiActionPerformed
        if(no_masuk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nomor Masuk Tidak Boleh Kosong");
        }else if(cmbnomorfaktur.getSelectedItem().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nomor Faktur Tidak Boleh Kosong");
        }

        if (!no_masuk.getText().equals("") && !cmbnomorfaktur.getSelectedItem().equals("")){
            try {
                Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/persediaan_barang","root","");
                koneksi.createStatement().executeUpdate("INSERT INTO tbl_barang_masuk (no_masuk, no_faktur, nama_supplier, nama_barang, jumlah, tanggal) VALUES ('" + no_masuk.getText() + "','" + cmbnomorfaktur.getSelectedItem()+ "', '" + nama_supplier.getText() + "', '" + nama_barang.getText() + "', '" + jumlah.getText() + "', '" + tanggalbarangmasuk.getText() + "')");
                reset();
                JOptionPane.showMessageDialog(null, "Input Barang Masuk Berhasil");
            } catch (SQLException ex) {
                Logger.getLogger(barang_keluar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_simpantransaksiActionPerformed

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang_masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbnomorfaktur;
    private javax.swing.JButton hapusbarangkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JTextField no_masuk;
    private javax.swing.JButton ok;
    private javax.swing.JButton simpantransaksi;
    private javax.swing.JTextField tanggalbarangmasuk;
    private javax.swing.JTable tblbarangmasuk;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        no_masuk.setText("");
        cmbnomorfaktur.setSelectedItem("");
        nama_supplier.setText("");
        nama_barang.setText("");
        jumlah.setText("");
        tanggalbarangmasuk.setText("");
    }
}
